# Generated by Django 4.2.1 on 2023-05-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, null=True)),
                ("gender", models.CharField(max_length=1, null=True)),
                ("date_of_birth", models.DateField()),
                ("industry", models.CharField(max_length=255)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("years_of_experience", models.IntegerField()),
            ],
        )
    ]
